CREATE TABLE IF NOT EXISTS users(
    user_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    nickname VARCHAR(30) NOT NULL UNIQUE,
    age INTEGER NOT NULL,
    gender VARCHAR(7) NOT NULL,
    first_name VARCHAR (30) NOT NULL,
    last_name VARCHAR (30) NOT NULL,
    email VARCHAR (30) NOT NULL UNIQUE,
    user_password VARCHAR(100) NOT NULL 
)